# Generated by Django 6.0.3 on 2026-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaiverity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
